---
title: "git_01"
author: "Wilhelmus Elersich"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

THERE are certain things - as, a spider, a ghost,  
The income-tax, gout, an umbrella for three -  
That I hate, but the thing that I hate the most  
Is a thing they call the Sea.  

Pour some salt water over the floor -

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Lo! the Spear-Danes’ glory through splendid achievements  
The folk-kings’ former fame we have heard of,  
How princes displayed then their prowess-in-battle.  
Oft Scyld the Scefing from scathers in numbers  
From many a people their mead-benches tore.  
Since first he found him friendless and wretched,  
The earl had had terror: comfort he got for it,  
Waxed ’neath the welkin, world-honor gained,  
Till all his neighbors o’er sea were compelled to  
Bow to his bidding and bring him their tribute:  
An excellent atheling! After was borne him  
A son and heir, young in his dwelling,  
Whom God-Father sent to solace the people.  
He had marked the misery malice had caused them,  
That reaved of their rulers they wretched had erstwhile  
Long been afflicted. The Lord, in requital,  
Wielder of Glory, with world-honor blessed him.  
Famed was Beowulf, far spread the glory  
Of Scyld’s great son in the lands of the Danemen.  
